app.directive 'contentInfo', ->
  {
    restrict: 'E'
    transclude: true
    scope: info: '='
    templateUrl: 'js/directives/contentInfo.html'
    link: (scope, element, attrs) ->

  }

# ---
# generated by js2coffee 2.2.0
