app.directive 'technologyInfo', ->
  {
    restrict: 'E'
    replace: true
    scope: info: '='
    templateUrl: 'js/directives/technologyInfo.html'
    link: (scope, element, attrs) ->

  }

# ---
# generated by js2coffee 2.2.0
