# A controller manages the app's data.
app.controller 'HomeController', [
  '$scope'
  'gameService'
  ($scope, gameService) ->
    # gameService is a dependency to the controller
    $scope.title = 'My Saved Games'
    gameService.getGames (data) ->
      angular.extend $scope, data
      return
    return
]

# ---
# generated by js2coffee 2.2.0
