app.controller 'UnitsController', [
  '$scope'
  'unitService'
  ($scope, unitService) ->
    $scope.title = 'Units'
    $scope.content = unitService.query()
    return
]

# ---
# generated by js2coffee 2.2.0
